import 'package:flutter/material.dart';

class Search extends StatefulWidget {
  const Search({Key? key}) : super(key: key);

  @override
  _SearchState createState() => _SearchState();
}

class _SearchState extends State<Search> {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.only(top: 20),
      child: GridView.count(
          crossAxisCount: 3,
          shrinkWrap: true,
          primary: false,
          padding: EdgeInsets.zero,
          crossAxisSpacing: 0.5,
          mainAxisSpacing: 0.5,
          childAspectRatio: 1,
          children: [
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
            Image.asset('assets/post.jpeg',
                width: double.infinity,
                height: double.infinity,
                fit: BoxFit.cover),
          ]),
    );
  }
}
